local specIdFunction = {
	[ 62] = MageArcane,
	[ 63] = MageFire,
	[ 64] = MageFrost,
	[ 65] = PaladinHoly,
	[ 66] = PaladinProtection,
	[ 70] = PaladinRetribution,
	[ 71] = WarriorArms,
	[ 72] = WarriorFury,
	[ 73] = WarriorProtection,
	[102] = DruidBalance,
	[103] = DruidFeral,
	[104] = DruidGuardian,
	[105] = DruidRestoration,
 	[250] = DeathKnightBlood,
 	[251] = DeathKnightFrost,
 	[252] = DeathKnightUnholy,
 	[253] = HunterBeastMastery,
 	[254] = HunterMarksmanship,
 	[255] = HunterSurvival,
 	[256] = PriestDiscipline,
 	[257] = PriestHoly,
 	[258] = PriestShadow,
 	[259] = RogueAssassination,
 	[260] = RogueOutlaw,
 	[261] = RogueSubtlety,
 	[262] = ShamanElemental,
 	[263] = ShamanEnhancement,
 	[264] = ShamanRestoration,
 	[265] = WarlockAffliction,
 	[266] = WarlockDemonology,
 	[267] = WarlockDestruction,
 	[268] = MonkBrewmaster,
 	[269] = MonkWindwalker,
 	[270] = MonkMistweaver,
 	[577] = DemonHunterHavoc,
 	[581] = DemonHunterVengeance,
}
AddFrameCallback(function ()
	local playerSpec = GetSpecializationInfo(GetSpecialization())
	specIdFunction[playerSpec]()
end)